import os
import logging
from dotenv import load_dotenv

load_dotenv(override=True)

logger = logging.getLogger(__name__)

# =========================
# Paths
# =========================

BASE_DIR = os.path.dirname(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
)
# BASE_DIR -> backend/

# =========================
# Model Selection
# =========================

MODEL_ARCHITECTURE = os.getenv("MODEL_ARCHITECTURE", "resnet18")

MODEL_PATHS = {
    "resnet18": os.path.join(BASE_DIR, "models", "brain_tumor_resnet18.pth"),
    "efficientnet_b3": os.path.join(
        BASE_DIR, "models", "brain_tumor_efficientnet_b3.pth"
    ),
}

NUM_CLASSES = 4


# =========================
# Classes
# =========================

CLASS_NAMES = ['glioma', 'meningioma', 'notumor', 'pituitary']

# =========================
# Image preprocessing
# =========================

IMAGE_SIZE = (224, 224)
MEAN = [0.485, 0.456, 0.406]
STD = [0.229, 0.224, 0.225]

# =========================
# LLM
# =========================

GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")

# =========================
# Upload limits
# =========================

MAX_UPLOAD_SIZE_MB = int(os.getenv("MAX_UPLOAD_SIZE_MB", "10"))
ALLOWED_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp"}

# =========================
# Authentication
# =========================

# JWT Settings — SECRET_KEY MUST be set via environment variable in production
_secret = os.getenv("SECRET_KEY", "")
if not _secret or _secret == "your-secret-key-change-this-in-production":
    logger.warning(
        "\n" + "=" * 60
        + "\n  WARNING: SECRET_KEY is not set or is using the default!\n"
        + "  Set a strong SECRET_KEY environment variable for production.\n"
        + "=" * 60
    )
    # Use a fallback for development only
    _secret = "dev-only-insecure-key-change-me"
SECRET_KEY = _secret

ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 60 * 24  # 24 hours

# Google OAuth Settings
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID", "")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET", "")
if not GOOGLE_CLIENT_ID:
    logger.warning("GOOGLE_CLIENT_ID is not set. Google OAuth will not work.")

# =========================
# Database
# =========================

DATABASE_PATH = os.path.join(BASE_DIR, "neuro_ai.db")

# =========================
# Medical Disclaimer
# =========================

MEDICAL_DISCLAIMER = (
    "DISCLAIMER: This report is generated by an artificial intelligence system "
    "and is intended for informational and educational purposes only. It does NOT "
    "constitute a medical diagnosis, professional medical advice, or treatment "
    "recommendation. All findings must be reviewed and validated by a qualified "
    "healthcare professional. Never rely solely on AI-generated analysis for "
    "clinical decisions."
)
